# Generated by Django 3.1.8 on 2021-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210604_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pickup_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
